ТЗ15 - 1 итерация
alexexus/java-shareit pull request #3
Opened 2023-05-20 05:03 UTC by alexexus

2023-05-21 09:25 UTC, kalitva requested changes

2023-05-21 09:25 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
Попробуй использовать спринговый `Specification` для фильтрация объектов БД вместо определения всех этих методов

https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl

2023-05-21 09:25 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (from == null || size == null) {
Как насчет использовать gurad clause?

https://www.codementor.io/@clintwinter/use-guard-clauses-for-cleaner-code-1rrsczgwxp

2023-05-21 09:25 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            try {
Думаю стоит завернуть в try только преобразование в энам, а не весь свич

2023-05-21 09:25 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                                required = false) Integer from,
На мой взгляд замудреное форматирование, почему бы не определить весь параметр на одной линии

2023-05-21 09:25 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +        if (item.getRequestId() != null) {
Пожалуйста, сделай сеттинг реквеста на основе как в указано в тз 14 в советах ментора

2023-05-21 09:25 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findByNameContainingIgnoreCaseAndAvailableIsTrueOrDescriptionContainingIgnoreCaseAndAvailableIsTrue(
Интересное решение, даже не думал что так можно. Но как насчет того, как выглядит вызов метода? Удобно ли будет читать?

2023-05-21 09:25 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>      private final BookingMapper bookingMapper;
Не пойму, у тебя мапперы и в сервисах и в контроллерах. Сделай единообразно чтобы мапперы были *либо в сервисах, либо в контроллерах*. Используй `@Transient` если в модель нужно добавить поле, которое не маппится на поле в БД

2023-05-21 09:25 UTC, kalitva commented on src/test/java/ru/practicum/shareit/booking/BookingControllerIT.java
> +class BookingControllerIT {
`BookingControllerIT --> BookingControllerIntefrationTest`

2023-05-21 09:25 UTC, kalitva commented on src/test/java/ru/practicum/shareit/request/ItemRequestRepositoryIT.java
> +@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
Не очень хорошая практика когда тесты зависят от порядка исполнения

2023-05-21 09:25 UTC, kalitva commented on src/test/java/ru/practicum/shareit/request/ItemRequestRepositoryIT.java
> +    @BeforeEach
Лучше делай это с помощью `@Sql`

2023-05-21 09:25 UTC, kalitva commented on src/test/java/ru/practicum/shareit/request/ItemRequestRepositoryIT.java
> +    private void cleanDb() {
Лучше с помощью `@Sql`. Поставь на уровне класса, фаза исполнения - после тестового метода

2023-05-21 09:25 UTC, kalitva commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +        verify(repository, times(1)).save(any(User.class));
Если можно без `any` то лучше без него. Проверь что в вызов пошел параметер `userToSave`

2023-05-21 09:25 UTC, kalitva commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +        when(repository.findById(anyLong())).thenReturn(Optional.of(expectedUser));
`anyLong() --> 1L` и в вызове `verify` передай `1L ` соответственно

2023-05-25 11:31 UTC, alexexus commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
Что-то я не понимаю как это делать, а главное зачем, если количество методов не изменится

2023-05-26 07:22 UTC, merged